/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mock.java.producer;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

public class App {

  public static void main(String[] args) throws ParseException {
    Options opts = new Options();
    opts.addOption("j", "job", true, "job name to publish");
    opts.addOption("r", "rc", true, "return code");

    CommandLineParser parser = new DefaultParser();
    CommandLine cmd = parser.parse(opts, args);

    if (!(cmd.hasOption("job") && cmd.hasOption("rc"))) {
      System.out.println("Missing either --job or --rc on the command line.");
      System.exit(1);
    }

    Producer p =
        Producer.getInstance(new String[] {"localhost:9092"}, "demo-topic", "java-producer-id");

    p.send(cmd.getOptionValue("job"), cmd.getOptionValue("rc"));

    p.close();

    System.out.println("Completed sending message.");
    System.exit(0);
  }
}
