/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mock.java.consumer;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

public class App {

  public static void main(String[] args) throws ParseException {
    Options opts = new Options();
    opts.addOption("fb", "from-beginning", false, "receives messages from offset 0");

    CommandLineParser parser = new DefaultParser();
    CommandLine cmd = parser.parse(opts, args);

    boolean fromBeginning = false;
    if (cmd.hasOption("from-beginning")) {
      fromBeginning = true;
    }

    Consumer c =
        Consumer.getInstance(
            new String[] {"localhost:9092"}, "demo-topic", "java-consumer-id", fromBeginning);

    c.listen();

    System.out.println("Completed receiving messages.");
    System.exit(0);
  }
}
